__author__ = 'sdeni'

import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)

PIN_AHEAD_LEFT_FORWARD = 31
PIN_AHEAD_LEFT_BACKWARD =  29
PIN_AHEAD_LEFT_PWM = 3

PIN_AHEAD_RIGHT_FORWARD = 35
PIN_AHEAD_RIGHT_BACKWARD = 33
PIN_AHEAD_RIGHT_PWM =  5
# -----------
PIN_BEHIND_LEFT_FORWARD = 16
PIN_BEHIND_LEFT_BACKWARD = 18
PIN_BEHIND_LEFT_PWM =  7

PIN_BEHIND_RIGHT_FORWARD = 23
PIN_BEHIND_RIGHT_BACKWARD = 21
PIN_BEHIND_RIGHT_PWM =  11

pins = [PIN_AHEAD_LEFT_FORWARD, PIN_AHEAD_LEFT_BACKWARD, PIN_AHEAD_RIGHT_FORWARD, PIN_AHEAD_RIGHT_BACKWARD,
        PIN_BEHIND_LEFT_FORWARD, PIN_BEHIND_LEFT_BACKWARD, PIN_BEHIND_RIGHT_FORWARD, PIN_BEHIND_RIGHT_BACKWARD]

GPIO.setup(pins, GPIO.OUT)
GPIO.output(pins, GPIO.LOW)

ACTION_GO_FORWARD = "ACTION_GO_FORWARD"
ACTION_GO_BACKWARD = "ACTION_GO_BACKWARD"
ACTION_STOP = "ACTION_STOP"